```
rethrow()
```

`catch` ブロック内から現在の例外を再スローします。再スローされた例外は、捕捉されなかったかのように伝播を続けます。

!!! note
    代替形式 `rethrow(e)` は、現在のバックトレースに代替の例外オブジェクト `e` を関連付けることを可能にします。しかし、これはエラー発生時のプログラムの状態を誤って表現するため、代わりに `throw(e)` を使用して新しい例外をスローすることをお勧めします。Julia 1.1 以降では、`throw(e)` を使用すると、スタック上の根本原因の例外が保持されることが説明されています [`current_exceptions`](@ref)。

