```
catch_backtrace()
```

現在の例外のバックトレースを取得し、`catch` ブロック内で使用します。
