```
error(msg...)
```

`string(msg...)`で構築されたメッセージを持つ`ErrorException`を発生させます。
